eureka:
  client:
    register-with-eureka: true
    fetch-registry: true

---

spring:
  config:
    activate:
      on-profile: info,docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://registry:8761/eureka/
  instance:
    hostname: REGISTRY-MICROSERVICE

---

spring:
  config:
    activate:
      on-profile: default
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
