spring:
  config:
    activate:
      on-profile: gatewayServer
   server:
    port: 8989
  cloud:
    gateway:
      routes:
        - id: server-service
          uri: lb://SERVER-MICROSERVICE
          predicates:
            - Path=/animal/**, /owner/**
        - id: another-server-service
          uri: lb://ANOTHER-SERVER-MICROSERVICE
          predicates:
            - Path=/collar/**
